return {
  mss("ii", "_{i}"),
  mss("jj", "_{j}"),
  mss("kk", "_{k}"),
  mss("ll", "_{l}"),
  mss("mm", "_{m}"),
  mss("nn", "_{n}"),
  mss("ri", "^{i}"),
  mss("rj", "^{j}"),
  mss("rk", "^{k}"),
  mss("rl", "^{l}"),
  mss("rm", "^{m}"),
  mss("rn", "^{n}"),
  mss("r0", "^{0}"),
  mss("r1", "^{1}"),
  mss("r2", "^{2}"),
  mss("r3", "^{3}"),
  mss("r4", "^{4}"),
  mss("r5", "^{5}"),
  mss("r6", "^{6}"),
  mss("r7", "^{7}"),
  mss("r8", "^{8}"),
  mss("r9", "^{9}"),
  msa("_", { t("_{"), i(1), t("}") }),
  mss("rtr", "^{T}"),
  mss("oo", "\\circ "),
  mss("rci", "^{\\circ}"),
  mss("ros", "^{\\ostar}"),
  mss("dul", "^{\\star}"),
  msa("rd", { t("^{"), i(1), t("}") }),
  msa("td", { t("^{("), i(1), t(")}") }),
  mss("reli", "\\operatorname{ri} "),
  mss("nlt", "\\operatorname{nullity} "),
  mss("epp", "\\operatorname{epi} "),
  mss("cxx", "\\amalg"),
  mss("pe", "\\prime")
}
